export const cantones: Record<string, string[]> = {
  Azuay: [
    'Cuenca',
    'Chordeleg',
    'El Pan',
    'Girón',
    'Guachapala',
    'Gualaceo',
    'Nabón',
    'Oña',
    'Camilo Ponce Enríquez',
    'Sigsig',
    'San Fernando',
    'Santa Isabel',
    'Pucará',
    'Sevilla de Oro',
  ].sort(),
  Bolivar: [
    'Guaranda',
    'Caluma',
    'Chimbo',
    'Chillanes',
    'Echeandía',
    'San Miguel',
    'San Pablo de Atenas',
  ],
  Caniar: ['Azogues', 'Cañar', 'El Tambo', 'La Troncal', 'Suscal'],
  Carchi: ['Tulcán', 'Bolívar', 'Espejo', 'Montúfar', 'San Pedro de Huaca'],
  Chimborazo: [
    'Alausí',
    'Chambo',
    'Chunchi',
    'Colta',
    'Cumandá',
    'Guamote',
    'Guano',
    'Pallatanga',
    'Penipe',
    'Riobamba',
  ],
  Cotopaxi: [
    'La Maná',
    'Latacunga',
    'Pangua',
    'Pujilí',
    'Salcedo',
    'Saquisilí',
    'Sigchos',
  ],
  ElOro: [
    'Machala',
    'Arenillas',
    'Atahualpa',
    'Balsas',
    'Chila',
    'El Guabo',
    'Huaquillas',
    'Marcabelí',
    'Pasaje',
    'Piñas',
    'Portovelo',
    'Santa Rosa',
    'Zaruma',
    'Las Lajas',
  ],
  Esmeraldas: [
    'Atacames',
    'Eloy Alfaro',
    'Esmeraldas',
    'Muisne',
    'Quinindé',
    'Rioverde',
    'San Lorenzo',
  ],
  Guayas: [
    'Balao',
    'Balzar',
    'Bucay',
    'Colimes',
    'Daule',
    'El Empalme',
    'El Triunfo',
    'Milagro',
    'Naranjito',
    'Naranjal',
    'Palestina',
    'Pedro Carbo',
    'Samborondón',
    'Santa Lucía',
  ],
  Imbabura: [
    'Antonio Ante',
    'Cotacachi',
    'Ibarra',
    'Otavalo',
    'Pimampiro',
    'San Miguel de Urcuquí',
  ],
  Loja: [
    'Calvas',
    'Catamayo',
    'Celica',
    'Chaguarpamba',
    'Espíndola',
    'Gonzanamá',
    'Loja',
    'Macará',
  ],
  LosRios: [
    'Baba',
    'Babahoyo',
    'Buena Fe',
    'Vinces',
    'Mocache',
    'Palenque',
    'Quinsaloma',
    'Urdaneta',
    'Ventanas',
    'Valencia',
  ],
  Manabi: [
    'Pedernales',
    'Jama',
    'San Vicente',
    'Sucre',
    'Chone',
    'Flavio Alfaro',
    'El Carmen',
    'Tosagua',
    'Rocafuerte',
    'Junín',
    'Pichincha',
    'Portoviejo',
    'Manta',
    'Santa Ana',
    '24 de Mayo',
    'Olmedo',
    'Montecristi',
    'Jaramijó',
  ],
  MoronaSantiago: [
    'Santiago de Méndez',
    'Taisha',
    'Limón Indanza',
    'Gualaquiza',
    'Morona',
    'Palora',
    'Sucua',
    'Huamboya',
    'Logroño',
  ],
  Napo: [
    'Archidona',
    'Carlos Julio Arosemena Tola',
    'El Chaco',
    'Tena',
    'Quijos',
  ],
  Orellana: ['Orellana', 'Aguarico', 'Joya de los Sachas', 'Loreto'],
  Pastaza: ['Arajuno', 'Mera', 'Pastaza', 'Santa Clara'],
  Pichincha: [
    'Distrito Metropolitano de Quito',
    'Cayambe',
    'Mejía',
    'Pedro Moncayo',
    'Pedro Vicente Maldonado',
    'Puerto Quito',
    'Rumiñahui',
    'San Miguel de Los Bancos',
  ],
  SantaElena: ['La Libertad', 'Salinas', 'Santa Elena'],
  Sucumbios: [
    'Cascales',
    'Cuyabeno',
    'Gonzalo Pizarro',
    'Lago Agrio',
    'Putumayo',
    'Shushufindi',
    'Sucumbíos',
  ],
  StoDomingo: ['Sto. Domingo', 'La Concordia'],
  Tungurahua: [
    'Ambato',
    'Baños',
    'Cevallos',
    'Mocha',
    'Patate',
    'Quero',
    'Pelileo',
    'Píllaro',
    'Tisaleo',
  ].sort(),
  ZamoraChinchipe: [
    'Centinela del Cóndor',
    'Chinchipe',
    'El Pangui',
    'Nangaritza',
    'Palanda',
    'Paquisha',
    'Yacuambi',
    'Yantzaza',
  ],
};

export const azuay: string[] = [
  'Cuenca',
  'Chordeleg',
  'El Pan',
  'Girón',
  'Guachapala',
  'Gualaceo',
  'Nabón',
  'Oña',
  'Camilo Ponce Enríquez',
  'Sigsig',
  'San Fernando',
  'Santa Isabel',
  'Pucará',
  'Sevilla de Oro',
].sort();
export const bolívar: string[] = [
  'Guaranda',
  'Caluma',
  'Chimbo',
  'Chillanes',
  'Echeandía',
  'San Miguel',
  'San Pablo de Atenas',
];
export const caniar: string[] = [
  'Azogues',
  'Cañar',
  'El Tambo',
  'La Troncal',
  'Suscal',
];
export const carchi: string[] = [
  'Tulcán',
  'Bolívar',
  'Espejo',
  'Montúfar',
  'San Pedro de Huaca',
];
export const chimborazo: string[] = [
  'Alausí',
  'Chambo',
  'Chunchi',
  'Colta',
  'Cumandá',
  'Guamote',
  'Guano',
  'Pallatanga',
  'Penipe',
  'Riobamba',
];
export const cotopaxi: string[] = [
  'La Maná',
  'Latacunga',
  'Pangua',
  'Pujilí',
  'Salcedo',
  'Saquisilí',
  'Sigchos',
];
export const elOro: string[] = [
  'Machala',
  'Arenillas',
  'Atahualpa',
  'Balsas',
  'Chila',
  'El Guabo',
  'Huaquillas',
  'Marcabelí',
  'Pasaje',
  'Piñas',
  'Portovelo',
  'Santa Rosa',
  'Zaruma',
  'Las Lajas',
];
export const esmeraldas: string[] = [
  'Atacames',
  'Eloy Alfaro',
  'Esmeraldas',
  'Muisne',
  'Quinindé',
  'Rioverde',
  'San Lorenzo',
];
export const guayas: string[] = [
  'Balao',
  'Balzar',
  'Guayaquil',
  'Colimes',
  'Daule',
  'El Empalme',
  'El Triunfo',
  'Milagro',
  'Isidro Ayora',
  'Naranjal',
  'Palestina',
  'Playas',
  'Samborondón',
  'Santa Lucía',
];
export const imbabura: string[] = [
  'Antonio Ante',
  'Cotacachi',
  'Ibarra',
  'Otavalo',
  'Pimampiro',
  'San Miguel de Urcuquí',
];
export const loja: string[] = [
  'Calvas',
  'Catamayo',
  'Celica',
  'Chaguarpamba',
  'Espíndola',
  'Gonzanamá',
  'Loja',
  'Macará',
];
export const losRios: string[] = [
  'Babahoyo',
  'Buena Fe',
  'Chone',
  'Mocache',
  'Palenque',
  'Quinsaloma',
  'Río Verde',
  'Ventanas',
];
export const manabi: string[] = [
  'Pedernales',
  'Jama',
  'San Vicente',
  'Sucre',
  'Chone',
  'Flavio Alfaro',
  'El Carmen',
  'Tosagua',
  'Rocafuerte',
  'Junín',
  'Pichincha',
  'Portoviejo',
  'Manta',
  'Santa Ana',
  'Olmedo',
  'Montecristi',
  'Jaramijó',
];
export const moronaSantiago: string[] = [
  'Santiago de Méndez',
  'Taisha',
  'Limón Indanza',
  'Gualaquiza',
  'Morona',
  'Sucua',
  'Huamboya',
  'Logroño',
];
export const napo: string[] = [
  'Archidona',
  'Carlos Julio Arosemena Tola',
  'El Chaco',
  'Tena',
  'Quijos',
];
export const orellana: string[] = [
  'Aguarico',
  'Joya de los Sachas',
  'Loreto',
  'Orellana',
];
export const pastaza: string[] = ['Arajuno', 'Mera', 'Pastaza', 'Santa Clara'];
export const pichincha: string[] = [
  'Cayambe',
  'Mejía',
  'Pedro Moncayo',
  'Pedro Vicente Maldonado',
  'Puerto Quito',
  'Quito',
  'Rumiñahui',
  'San Miguel de Los Bancos',
];
export const santaElena: string[] = ['La Libertad', 'Salinas', 'Santa Elena'];
export const sucumbios: string[] = [
  'Cascales',
  'Cuyabeno',
  'Gonzalo Pizarro',
  'Lago Agrio',
  'Putumayo',
  'Shushufindi',
  'Sucumbíos',
];
export const stoDomingo: string[] = ['Sto.Domingo', 'La concordia'];
export const tungurahua: string[] = [
  'Ambato',
  'Baños',
  'Cevallos',
  'Mocha',
  'Patate',
  'Quero',
  'Pelileo',
  'Píllaro',
  'Tisaleo',
];
export const zamoraChinchipe: string[] = [
  'Centinela del Cóndor',
  'Chinchipe',
  'El Pangui',
  'Nangaritza',
  'Palanda',
  'Paquisha',
  'Yacuambi',
  'Yantzaza',
];
